[lib]

[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clokwerk = "0.4.0"
ethers = "2.0.11"
eyre = "0.6.11"
serde = "1.0.195"
serde_json = "1.0.111"
